// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaFCpJFujAHG1PM_gU8b_4v0pi-uVX8lE',
    appId: '1:779355817473:web:ebdd595c883e8b6808a200',
    messagingSenderId: '779355817473',
    projectId: 'minibot-29aa5',
    authDomain: 'minibot-29aa5.firebaseapp.com',
    storageBucket: 'minibot-29aa5.firebasestorage.app',
    measurementId: 'G-LEEWXNMGTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtReAswvFYmBicBWvusMz3mAkSNait8XI',
    appId: '1:779355817473:android:0e5d73ef60760f0208a200',
    messagingSenderId: '779355817473',
    projectId: 'minibot-29aa5',
    storageBucket: 'minibot-29aa5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj2PyMEkJcR7G-arADm1lL_bMHV6GKu7Y',
    appId: '1:779355817473:ios:b5ad2e6c80d6532508a200',
    messagingSenderId: '779355817473',
    projectId: 'minibot-29aa5',
    storageBucket: 'minibot-29aa5.firebasestorage.app',
    iosBundleId: 'com.example.minibotApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj2PyMEkJcR7G-arADm1lL_bMHV6GKu7Y',
    appId: '1:779355817473:ios:b5ad2e6c80d6532508a200',
    messagingSenderId: '779355817473',
    projectId: 'minibot-29aa5',
    storageBucket: 'minibot-29aa5.firebasestorage.app',
    iosBundleId: 'com.example.minibotApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaFCpJFujAHG1PM_gU8b_4v0pi-uVX8lE',
    appId: '1:779355817473:web:b1f055ba06b5880708a200',
    messagingSenderId: '779355817473',
    projectId: 'minibot-29aa5',
    authDomain: 'minibot-29aa5.firebaseapp.com',
    storageBucket: 'minibot-29aa5.firebasestorage.app',
    measurementId: 'G-NCRHFXFTK1',
  );
}
